### ISSUE TITLE
湖南省监局需求更改

### ISSUE THREAD

**Issue by booluo** [GKZX-HN/pmsystem_hunan#1]
重要罪犯、三类犯承办单流程只要走到处领导批示这一栏，需要把局评审会和局领导批示这两栏去掉；另外需要在处领导批示前面需要加一个处评审委员会意见。

**Comment by GKCaoShuai** [comment]
1 修改数据库表tbflow_deliver字段 DNODEID，  处长同意流程的下一节点DNODEID 由N0012变更为1，其余不变
2 修改罪犯减刑（假释）呈批处理表 删除局评审会和局领导批示这两栏在处领导意见栏前添加处评委会意见栏

**Comment by GKCaoShuai** [comment]
在二次开发的表单管理模块，新增新表单，在资源管理-》减刑假释（省局）模块，修改所有需要使用新表单地方的名字

**Comment by GKCaoShuai** [comment]
update  Tbflow_Deliver t set t.dnodeid='1' where t.resid='702687' and t. snodeid='N0011' and t.dnodeid='N0012' and t.departid='4300'

**Comment by GKCaoShuai** [comment]
剩下的就是先保存老的表单至本地，再用新表单替换老表单

**Comment by yangbo1987** [comment]
按照已经更新 但是 新的问题出现 有个人是无期死缓办案流程 他的 局评审会和局领导 这两栏不见

**Comment by GKCaoShuai** [comment]
[关于整改重点罪犯与无期死缓步骤.docx](https://github.com/GKZX-HN/pmsystem_hunan/files/1421261/default.docx)

**Comment by GKCaoShuai** [comment]
AIP文件、 class 文件 无法上传

**Comment by yangbo1987** [comment]
处务会的几点你要考虑：1处务会记录 2处务会你现在只能操作在承办单 ,并不能反应到承办人登记表和审核表 ，而承办人登记表和审核表是最终会到档案记录里面去的 比较重要  所以tab页承办人登记表和审核表方面也要考虑同步 3 王柏林科长说的是处务会归承办人来牵头 以前的评审会是单独弄一个节点（即有专门的sjpsh账号来处理这一个环节）来处理的 这一点你要权衡下 4 处务会需同时考虑无期死缓和重要罪犯这两个流程都能使用

**Comment by GKCaoShuai** [comment]
关于增加处务会这一级别的审批，涉及到的四张表单，以及相应的流程已经配完了，但是从监狱上传来的罪犯数据，没有引用我自己画的的登记表和审核表，数据同步也就无法继续进行，需要大幅度的改动的监狱的功能模块，在不确定监狱模块改动后是否会影响到其他的功能使用的情况下，无法进行监狱办案流程的修改工作。
