### ISSUE TITLE
建议书批量签章问题

### ISSUE THREAD

**Issue by w4824112w** [GKZX-HN/pmsystem_hunan#10]
在监狱长一级选择建议书（正常）进行批量签字会提示签章失败，选择建议书（无行距）签字是成功了，但是建议书内容变成乱码
![4ec5463085b42151a4ad1d42baec849c](https://user-images.githubusercontent.com/14324300/31869464-d1207284-b7da-11e7-8514-da7f51d01e98.png)
![2846e835db95312b7f3ad897d4acf0e7](https://user-images.githubusercontent.com/14324300/31869465-d152fd12-b7da-11e7-87b0-1cee1cd92fc6.png)

**Comment by lachengdong** [comment]
解决思路
从截图来看，查询方案中的tbcode0 tbcode1 tbcode2 是可以正确展示出来的，只有tbcode3中的模板数据是显示未解析的，所以解决方案如下
1.更改 tbcode3中的查询方案，最后附上查询方案。
2.重新安装插件，清理缓存。

附录 tbcode3 查询方案

查询模板

select 
       tbo.docconent as docconent
  from TBFLOW_OTHER_FLOW tof,
       TBFLOW_BASE_OTHER tbo

 where tof.flowdraftid = '@@{flowdraftid}'
   and tof.tempid = 'jailcommute'
   and tof.otherid = tbo.otherid
