### ISSUE TITLE
法监互联裁定书

### ISSUE THREAD

**Issue by legolasedwin** [GKZX-HN/pmsystem_hunan#11]
法院发送到监狱裁定书存在异常，数量不正确，内容为空。如：津市收到124份，内容全为空；德山100多个犯人，收到了300份裁定书。

**Comment by penghaining93** [comment]
1.数量不正确，如果法院发过来的裁定和送达有问题，需要法院重发，重发之前需要清除相关数据
  解决方案 delete from tbdata_archives t where batchid='批次编号' and crimid ='罪犯编号'
                 delete from from tbxf_ruling t where batchid='批次编号' and crimid ='罪犯编号'
2.内容为空，首先确定是否配置tomcat虚拟路径（在 部署补充注意事项 word中有），如果还是打不开裁定，去D:\jxjs\jxjscourtzipfile确认是否接收到了法院的文书
查看courtJointPrisonconfig.properties这个文件是否更新，文件中这个属性名称courtjxjsxmlpath，查看tbxf_ruling这个表是否更新，rulingdate这个字段是否为varchar2类型，如果以上2个文件存在错误，会导致该罪犯裁定接收失败
