### ISSUE TITLE
呈批处理表数据展示问题

### ISSUE THREAD

**Issue by w4824112w** [GKZX-HN/pmsystem_hunan#14]
财产补录后，呈批处理表未显示本次缴纳罚金信息，本次履行没显示。
![81c92f4c07566e7d962016f8f10ee092](https://user-images.githubusercontent.com/14324300/31879604-6e55d2b2-b810-11e7-906c-ac9a7e6779ca.png)
![dec4c2506dc80bc3cb72f76d4afe61eb](https://user-images.githubusercontent.com/14324300/31879605-6ea21834-b810-11e7-9f62-8c2a98020230.png)

**Comment by lachengdong** [comment]
这个问题发生的可能性是
1. 雁北监狱的代码没有更新（建议更新）
2.雁北监狱对应的 3000183  查询方案的查询基本信息sql组不是最新的

下面我粘上可以正确显示的查询基本信息sql组（修改前请备份原有的）


select                        
   NVL(uv.DEPARTNAME,'/') as jailname,
   NVL(uv.ORGNAME2,'/') as orgname,
   NVL(uv.crimname,'/') as cbiname,
   NVL(uv.crimid,'/') as crimid,
   NVL(uv.crimid,'/') as criminalid,
   NVL(uv.daiburiqistr,'/') as arrestdate,
   NVL(uv.jiyariqistr,'/') as detaindate,
   NVL(uv.fileno,'/') as fileno,
   NVL(uv.yuanpanxingqiqiristr,'/') as sentencestime,
   NVL(getage(uv.birthday),'/') as age,
   NVL(uv.usedname,'/') as usedname,
   NVL(uv.crimsex,'/')  as cbigender,
   NVL(uv.wenhuachengdu,'/')  as caieducation,
   NVL(uv.birtharea,'/') as birtharea,
   NVL(uv.countryarea,'/')  as cbinativeplaceaddress,
   NVL(uv.minzu,'/')  as cbination,
   NVL(uv.chushengriqistr,'/')  as aipbirthday,
   NVL(uv.jiatingzhuzhi,'/')  as familyaddress,
   NVL(uv.buqianzhiwu,'/')  as aiformerduty,
   NVL(uv.maritalstatus,'/')  as caiformermarriage,
   NVL(uv.zhengzhimianmao,'/')   as caipoliticalappearance,
   NVL(uv.zhiwujibie,'/')  as caiformerlevel,
   NVL(uv.rujianriqistr,'/')  as inprisondate,
   NVL(uv.yuanpanzhixingshijianstr,'/')  as executiondate,
   NVL(uv.yuanpanpancairiqistr,'/')  as judgedate,
   NVL(uv.yuanpanxingqi,'/')  as zhuxing,
   NVL(uv.xingqibiandong1,'/')  as sentencechageinfo,
   NVL(uv.xianzhixingshijian,'/')  as scjxcddate,
   DECODE(uv.shangcijianxingfudu,'　','/','','/',uv.shangcijianxingfudu)  as scjxfd,
   NVL(uv.zuiming,'/')  as causeaction,
   NVL(uv.yuanpanxingqiqiristr,'/')  as xingqiqizhi,
   NVL(uv.yuanpanxingqizhiristr,'/')  as sentenceetime,
   NVL(uv.fanzuishijianstr,'/')  as crimedate,
   REPLACE(DECODE(uv.yuanfajin,'','/','/','/',uv.yuanfajin||'元'),'元元','元')  as forfeit,
   NVL(uv.yuanminpei,'/')  as compensation,
   NVL(uv.fanzuishishi,'/')  as crimeface,
   REPLACE(DECODE(uv.lvxingfajin,'','/','/','/',uv.lvxingfajin||'元'),'元元','元') as payment,
   NVL(uv.lvxingminpei,'/')  as fulfilcompensation, 
     
   NVL(uv.yuanmoshou,'/')  as  forfeitureproperty,
   NVL(uv.lvxingmoshou,'/')  as  expropriation,
   NVL(uv.fayuanpancai,'/')  as firsttrialsum,
   NVL(uv.yuanpanfayuan,'/')  as judgmentname,
   NVL(uv.fanzuiqianke,'/')  as  crimerecord,
   NVL(uv.daibujiguan,'/')  as arrestauthority,
   NVL(uv.yuanpanzihao,'/')  as  cjicourtnumber,
   NVL(uv.yuanpanzhuizang,'/') as stolenmoney,
   NVL(uv.lvxingzhuizang,'/') as returnloot,
   NVL(uv.bencizhuizang,'/') as thisreturnloot,
   
   uv.leifan as checkboxisrecidivism,--累犯
   uv.xidushi as checkboxtakedrugs,       --吸毒史
   
   F_GET_BOOL4_CHECK_BOX(uv.weichengnian) as checkboxisminor,--是否未成年
   F_GET_BOOL4_CHECK_BOX(uv.laofan) as checkboxoldprisoner, --老犯
   F_GET_BOOL4_CHECK_BOX(uv.bingfan) as checkboxillprisoner,     --病犯
   F_GET_BOOL4_CHECK_BOX(uv.canfan) as checkboxdeformityprisoner, --残犯
   F_GET_BOOL4_CHECK_BOX(uv.shenghuonanyizili) as checkbox_shnyzl, --生活难以自理
   F_GET_BOOL4_CHECK_BOX(uv.sangshilaodongnengli) as checkbox_jbssldnl, --基本丧失劳动能力
   F_GET_BOOL4_CHECK_BOX(uv.xianzhijianxing) as checkboxisremission, --限制减刑
   
   F_GET_BOOL4_CHECK_BOX(uv.guanfan) as checkboxrecidivist,--惯犯
   F_GET_BOOL4_CHECK_BOX(uv.dupin) as checkboxdrugs, --毒品犯
   F_GET_BOOL4_CHECK_BOX(uv.sizuiyishang) as checkboxoverfourcrimes, --犯四罪以上
   F_GET_BOOL4_CHECK_BOX(uv.yanzhongweiji) as checkboxseriousviolations,--严重违纪
   F_GET_BOOL4_CHECK_BOX(uv.shuzuibingfa) as checkboxcombinedpunishment,--数罪并罚并有两罪在五年以上
   F_GET_BOOL4_CHECK_BOX(uv.yanzhongbaoli) as checkboxviolence,--严重暴力犯罪
   F_GET_BOOL4_CHECK_BOX(uv.weianfan) as checkboxdangerous,--危安犯
   F_GET_BOOL4_CHECK_BOX(uv.zhiwufan) as checkboxpostcrime, --职务犯罪
   F_GET_BOOL4_CHECK_BOX(uv.jinrongfan) as checkboxundermine,--破坏金融管理秩序和金融诈骗犯罪
   F_GET_BOOL4_CHECK_BOX(uv.sheheifan) as checkboxunderworld,  --涉黑犯罪
   F_GET_BOOL4_CHECK_BOX(uv.zhongdianguanzhu) as checkboxfocus,   --重点关注
   F_GET_BOOL4_CHECK_BOX(uv.meitiguanzhu) as checkboxmediaattention, --媒体关注 
   F_GET_BOOL4_CHECK_BOX(uv.zishashi) as checkboxsuicide, --       自杀史
   F_GET_BOOL4_CHECK_BOX(uv.tuotaoshi) as checkboxescapes,   --脱逃史
   F_GET_BOOL4_CHECK_BOX(uv.xijingshi) as checkboxassaultepolice,   --袭警史

   @{_username} as suname,
        
   F_PUBLIC_GET_RESUME('@@{applyid}') gerenjianli,
   F_PUBLIC_GET_SOCIALRELATION('@@{applyid}') shehuiguanxi,
   
   (CASE
     WHEN REPLACE(uv.yuanminpei, '/', '') IS NOT NULL
     THEN REPLACE(REPLACE(DECODE(uv.benciminpei, '', '/', uv.benciminpei),'/、', ''), '/、','')
     ELSE DECODE (uv.benciminpei, '', '/', uv.benciminpei)
   END) AS thiscivil,       
             
  (CASE
    WHEN REPLACE (uv.yuanminpei, '/', '') IS NULL AND REPLACE (uv.YUANFAJIN, '/', '') IS NOT NULL
     THEN
        REPLACE(REPLACE(DECODE(uv.bencifajin,'', '/', '/', '/',uv.bencifajin || '元'), '元元','元'), '/、', '')
     ELSE
        REPLACE(DECODE (uv.bencifajin,'', '/','/', '/', uv.bencifajin || '元'),'元元','元')
   END) AS thisrecovered,

  (CASE
     WHEN REPLACE(uv.yuanminpei, '/', '') IS NULL AND REPLACE(uv.yuanfajin, '/', '') IS NULL AND REPLACE(uv.yuanmoshou, '/', '') IS NOT NULL
     THEN
        REPLACE(REPLACE (DECODE (uv.bencimoshou, '', '/', uv.bencimoshou),'/、',''),'/、','')
     ELSE
        DECODE(uv.bencimoshou, '', '/', uv.bencimoshou)
   END) AS thisexpropriation,
   
  uv.bencizhuizang AS bencizhuizang
  
from UV_CRIMINAL_INFO uv
where uv.CRIMID = '@@{applyid}'
