### ISSUE TITLE
承批处理表，考核计分同步错误

### ISSUE THREAD

**Issue by legolasedwin** [GKZX-HN/pmsystem_hunan#19]
女子监狱承批处理表中，犯人考核计分扣分情况错误，本录入扣分90，表单内容显示80分，还有10分查看数据库为TBXF_SENTENCEXXX 的表中 ENDTIME 这个考核时间错误，本已经设置为了第4批次立案，此次为考核计分假如为2017年6月30日，而此人此字段时间为2017年3月31日，为第三批次考核止日，故造成这个考核分统计情况不对原因为设置批次时候，考核止日未全部更新，修改代码处理下，这个很快。

**Comment by guoshipeng** [comment]
![qq 20171120180414](https://user-images.githubusercontent.com/32731000/33012918-3debaf3e-ce1d-11e7-9fd3-294a1b5336e0.png)
