### ISSUE TITLE
重要罪犯、三类犯省局处长审批完案子后该案子不知道去向

### ISSUE THREAD

**Issue by booluo** [GKZX-HN/pmsystem_hunan#21]
重要罪犯、三类犯由省局处长审批完后的正常流程是这样的：处长同意后提交给重要罪犯、三类犯的承办人，然后再由重要罪犯、三类犯的承办人发送监狱。
目前的问题是：省局处长审批完后保存提交后该案件不知道去向了。用各级用户登录都找不到该案件的办理，在案件查看只能看到该案件的最后痕迹记录是刑罚处长同意。
![default](https://user-images.githubusercontent.com/25612489/32308034-a4a2f182-bfbe-11e7-88c2-b93085d33913.jpg)

**Comment by GKCaoShuai** [comment]
重要罪犯在处长审批后流程就结束了，处长审批后的重要罪犯，在其他用户登陆后无法办理是正常的，只需要承办人登陆发送监狱就行
注（注意罪犯的批次，批次不对还是找不到罪犯）
