### ISSUE TITLE
省局退回的案子，在监狱那边看不到已经退回的案子的问题

### ISSUE THREAD

**Issue by booluo** [GKZX-HN/pmsystem_hunan#22]
问题描述：省局承办人把案子退回给监狱，在省局案件查看中的办案进程中可以是到监狱长办理中了，但是监狱反馈：他们自己的页面上（页面以刷新）该案子显示是在省局立案中。

**Comment by guoshipeng** [comment]
监狱数据库：select * from tbflow_deliver t where t.snodeid='N0009' for update
省局立案否决，省局立案退回  TEXT3 栏目里面 “省局立案中” 修改为  “监狱长办理中”
