### ISSUE TITLE
由监狱报送省局立案的案子，案子跑错通道的问题

### ISSUE THREAD

**Issue by booluo** [GKZX-HN/pmsystem_hunan#23]
问题描述：监狱把案子报送省局后，由于省局承办人是两个不同用户立案（sjcbr,sjcbr2）分别立案死缓无期、重要罪犯三类犯的案子。现在的问题是在报送某批案子后，这批案子本来是死缓无期的案子，报送省局后这批案子本该由sjcbr这个用户立案的，但是这批案子会出现其中的几个案子会跑到重要罪犯三类犯的通道中由sjcbr2这个用户立案；有些案件是重要罪犯、三类犯由sjcbr2立案，但是其中有些案件会跑到死缓无期的通道，有sjcbr这个用户立案。

**Comment by lijin3096** [comment]
回复啊？

**Comment by lachengdong** [comment]
省局立案两个承办人所用的是一个立案，实现的是所有的立案都在一个列表中，而且筛选功能测试过是正常筛选的。

**Comment by lachengdong** [comment]
此问题已经解决，但是修改了好几处代码和配置过程。我会上传代码到github上。

具体步骤较为繁琐，需要在省局要修改这个问题的话 直接联系我
