### ISSUE TITLE
桂阳监狱建议书问题

### ISSUE THREAD

**Issue by yangbo1987** [GKZX-HN/pmsystem_hunan#24]
建议书最后一段显示不完整，在建议书菜单中重新保存后，进行预览 建议书显示完整（但是没有公章了） 在批量签章中 对建议书进行签章后  建议书最后一段又显示不完整了（公章有了）

![202](https://user-images.githubusercontent.com/14324300/32644078-5b9e6a72-c61a-11e7-92fc-a00ef014bdbe.jpg)
![201](https://user-images.githubusercontent.com/14324300/32644209-27b0b2e6-c61b-11e7-955c-385e6b6a9761.jpg)

**Comment by lachengdong** [comment]
1.在建议书中签章保存成功后可以通过另一个建议书来查看签章成功后的预览。
2.问题中第一张图片所示的应该是盖章位置太靠上。把最后一排挤上去导致的残缺。

**Comment by GKZX** [comment]
签章应该出现在该出现的位置，客户看建议书肯定是要确定签章在该有的位置，这种让客户去别的建议书看预览的办法不是解决办法

**Comment by lachengdong** [comment]
此问题存在业务逻辑方面问题，无法达到在预览里面查看签章的效果。

**Comment by lachengdong** [comment]
预览功能是对编辑页面可修改的内容提供的预览，里面的签章成功后，再一次进入预览不会显示，因为再一次进入预览还是对的可修改内容大字段的修改信息预览（本次的大字段是没有签章过得信息），所以没有签章成功的展示，如果要看展示，必须要通过查签章成功后的大字段（是两个不同的大字段）。 总的来说 这块业务逻辑不允许再次预览可以看到签章

**Comment by lachengdong** [comment]
建议书批量签章的问题解决方法

1.监狱的章可能是太大了，导致签章后的建议书末尾行往上顶两格造成的，建议缩小一下监狱的章。
2.监狱书 湖南省监狱减刑假释建议书报表中 所留的签章位置往下拖一下。

综合以上两条解决办法，此问题基本能解决
