### ISSUE TITLE
德山监狱  基本信息（罪犯:雷鹏）无法提交

### ISSUE THREAD

**Issue by yangbo1987** [GKZX-HN/pmsystem_hunan#27]
管教操作雷鹏的基本信息，页面打开会提示浏览器的错误信息，点击确定或否后，页面能加载完成，提交后显示成功， 但是实际后台报错  具体见图。另外修改applyName applyId两个字段允许为空后，仍然显示tempid不能为空
另据彭英涛说，就算这么全部放开字段的约束，数据到下一级后，任然某些表无数据，导致下一级与管教这个流程来回无法走通，具体情况可咨询彭英涛
![1](https://user-images.githubusercontent.com/14324300/33156302-7ad47562-d033-11e7-82f8-6d92437654b1.jpg)
![2](https://user-images.githubusercontent.com/14324300/33156303-7b05eca0-d033-11e7-93e8-c1d45cfd6ca1.jpg)
![3](https://user-images.githubusercontent.com/14324300/33156304-7b390464-d033-11e7-8588-bdda9d4c26e9.jpg)

**Comment by lachengdong** [comment]
错误分析
1.在大字段传输的过程中对照片解析量过大的数据无法正常传输，在本次的错误中体现出照片超过1M的都会无法传输，上述的错误图片是因为大图片导致大字段不能被接收，从大字段接收的applyname applyID才会显示为空 。

解决思路：
对改罪犯的照片重新选择，建议在150K以内

照片路径   D:\criminalphotos  选择对应的照片，重新拍照或者照片处理后把原照片替换，不改照片名！
