### ISSUE TITLE
罪犯雷鹏，基本信息无法提交

### ISSUE THREAD

**Issue by penghaining93** [GKZX-HN/pmsystem_hunan#29]
罪犯雷鹏，基本信息无法提交，状态为“未处理”，彭英涛删除后重新新增，则只能查看，任何操作按钮都无效

**Comment by lachengdong** [comment]
错误分析
1.在大字段传输的过程中对照片解析量过大的数据无法正常传输，在本次的错误中体现出照片超过1M的都会无法传输，上述的错误图片是因为大图片导致大字段不能被接收，从大字段接收的applyname applyID才会显示为空 。

解决思路：
对改罪犯的照片重新选择，建议在150K以内

照片路径 D:\criminalphotos 选择对应的照片，重新拍照或者照片处理后把原照片替换，不改照片名！
