### ISSUE TITLE
呈批处理表中的从宽情况处

### ISSUE THREAD

**Issue by penghaining93** [GKZX-HN/pmsystem_hunan#30]
呈批处理表中的从宽情况处，未成年、基本丧失劳动能力、生活难以自理，勾选后不能同步到审核表、阅卷登记、汇总表、公示、名册中

**Comment by guoshipeng** [comment]
[审核表中健康状况单元格修改.zip](https://github.com/GKZX-HN/pmsystem_hunan/files/1546276/default.zip)
