### ISSUE TITLE
案件办理中的TAB页面案件办理的问题

### ISSUE THREAD

**Issue by legolasedwin** [GKZX-HN/pmsystem_hunan#8]
案件办理页面，从严情节栏目中，主犯这个CHECKBOX，即使基本信息中主犯栏目勾选了同步取的数据也不会勾选上这个，在数据方案中查询后，发现是存储过程对应的没有写主犯对应的CHECKBOX，查询页面命名，修改即可，速修改。

**Comment by lachengdong** [comment]
1.数据库执行 
语句    select * from tbflow_deliver t where t.flowdefid='other_zfjyjxjssp' and t.snodeid='0'  and t.departid ='4309' for update
在 TEXT2 加   ,checkboxprincipalaccessory 保存提交
