### ISSUE TITLE
财产补录列表查看数据错误

### ISSUE THREAD

**Issue by legolasedwin** [GKZX-HN/pmsystem_hunan#9]
补录财产型数据，假如法院没有单据号，只有判裁文书，单据号一栏填写格式为：（湘）XX市第（XXX号）文书，保存为成功，但是此条数据点击查看筛查不出来，查看后台为此条件显示为乱码，故查询不到数据，无法显示。

**Comment by GKCaoShuai** [comment]
开发环境没有该现象
